arch:
  - arm64
os: linux
dist: focal
git:
  depth: false

language: bash

services:
  - docker
  
script:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
  - docker build -t moussavdb/application-retro-website:latest .
  - docker push moussavdb/application-retro-website:latest .

