arch:
  - arm64
os: linux
dist: focal

language: generic

services:
  - docker

before_install:
  - docker build -t moussavdb/application-retro-website:latest -t .
script:
  - docker images moussavdb/application-retro-website
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker pushmoussavdb/application-retro-website:latest;

